# Generated by Django 4.2.30 on 2026-05-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_update_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
