# Generated by Django 4.2.30 on 2026-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challange',
            field=models.FloatField(default=3.0),
        ),
    ]
