# Generated by Django 4.2.30 on 2026-05-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_challange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='challange',
        ),
    ]
